### ISSUE TITLE
section 1 grammar mistake

### ISSUE THREAD

**Issue by janehmueller** [jjanetzki/Feature-Extraction-for-Business-Entity-Linking-in-Newspaper-Articles#1]
In [section 1, line 10](https://github.com/jjanetzki/Feature-Extraction-for-Business-Entity-Linking-in-Newspaper-Articles/blob/master/Sections/section_1.tex#L10):

- `Jan Ehmüller, Alec Schneider and me have developed a system that solves the first two tasks.`
should be
- `Jan Ehmüller, Alec Schneider and I have developed a system that solves the first two tasks.`

**Comment by janetzki** [comment]
THX 👍
